export const colorFixture: string[] = [
  "primary",
  "primaryDark",
  "primaryLight",
  "secondary",
  "secondaryDark",
  "secondaryLight",
  "tertiary",
  "tertiaryDark",
  "tertiaryLight",
  "grayDark",
  "gray",
  "grayLight",
  "offWhite",
  "white",
  "black",
];
