<?php

declare(strict_types=1);

namespace ChildTheme\Providers\Shop\Support;

/**
 * Buyer-facing transactional emails sent through wp_mail (→ msmtp →
 * Gmail SMTP relay → recipient). Every method sets the `From:` via
 * per-send headers rather than a global `wp_mail_from` filter — this
 * keeps portfolio-side or plugin-driven emails on whatever From they'd
 * otherwise use. Only shop-driven mail wears the itzenzoTTV identity.
 *
 * Fire-and-forget: send failures are logged via wp_mail's own error
 * path (PHPMailer logs) but never raised — these emails are nice-to-
 * have parallel notifications to the Discord DM, not the critical
 * path. A missing/bouncing email shouldn't break checkout, RTS, or
 * Make-an-Offer.
 *
 * Plain-text only by design. No HTML template engine, no attachments,
 * no inline images. Buyers who want a "real" receipt get the Stripe
 * receipt (post-PR-1) which is auto-generated by Stripe with formatting.
 */
class MailNotifications
{
    /**
     * The From: header every shop-driven email uses. Matches the alias
     * verified in Gmail "Send mail as" + the `from` line in
     * /etc/msmtprc on the droplet. If you bump this, update both
     * places + the seed-itzenzo-pages.php content referring to it.
     */
    private const FROM_HEADER = 'From: itzenzoTTV <noreply@itzenzo.tv>';

    /**
     * Send a confirmation email to a buyer who just submitted a
     * Make-an-Offer form on /collection. Mirrors the Discord DM that
     * already fires for the operator — closes the loop for buyers who
     * don't use Discord.
     *
     * @param array{
     *   email: string,
     *   card_title: string,
     *   offer_amount: string,
     *   message?: string,
     * } $data
     */
    public static function sendOfferConfirmation(array $data): bool
    {
        $email = (string) ($data['email'] ?? '');
        $cardTitle = (string) ($data['card_title'] ?? '');
        $offerAmount = (string) ($data['offer_amount'] ?? '');
        $buyerMessage = (string) ($data['message'] ?? '');

        if (!$email || !is_email($email)) {
            return false;
        }

        $subject = sprintf('We got your offer on %s — itzenzoTTV', $cardTitle);

        $lines = [
            sprintf("Hey — thanks for the offer on %s.", $cardTitle),
            '',
            sprintf('You offered: %s', $offerAmount),
        ];
        if ($buyerMessage !== '') {
            $lines[] = '';
            $lines[] = 'Your note:';
            $lines[] = '  ' . $buyerMessage;
        }
        $lines = array_merge($lines, [
            '',
            'I review offers between live shows and reply directly. If the number works, I send a Stripe checkout link for that exact amount. If not, I might counter or pass — either way you hear back.',
            '',
            'Reply to this email if you want to add context, or DM @itzenzottv on Discord.',
            '',
            '— Vinny @ itzenzoTTV',
            'https://itzenzo.tv/collection',
        ]);

        return self::send($email, $subject, implode("\n", $lines));
    }

    /**
     * Send a confirmation email to a buyer who just submitted a
     * Request to See on a card. The Discord queue entry happens
     * regardless; this is the email parallel for buyers without
     * Discord, plus a paper trail for anyone who wants one.
     *
     * @param array{
     *   email: string,
     *   card_title: string,
     * } $data
     */
    public static function sendCardRequestConfirmation(array $data): bool
    {
        $email = (string) ($data['email'] ?? '');
        $cardTitle = (string) ($data['card_title'] ?? '');

        if (!$email || !is_email($email)) {
            return false;
        }

        $subject = sprintf('We got your Request to See — %s', $cardTitle);

        $lines = [
            sprintf("Hey — your request to see %s is queued.", $cardTitle),
            '',
            "We'll feature this card live on our next show on Whatnot so you can see edges, surface, and holo shift before you buy. No commitment — just close the tab if it's not the one for you.",
            '',
            'Live shows run Monday, Tuesday, and Wednesday at 8 PM EST on Whatnot. Catch the show at https://whatnot.com/user/itzenzottv.',
            '',
            "We'll email you when the card is shown. If you want a louder ping, link your Discord account and we'll DM you the moment it hits the table.",
            '',
            '— itzenzoTTV',
            'https://itzenzo.tv/cards',
        ];

        return self::send($email, $subject, implode("\n", $lines));
    }

    /**
     * Internal send — wraps wp_mail with the consistent From header +
     * plain-text content-type. Returns the wp_mail result (true on
     * accept-for-delivery, false on local failure). Catches throwable
     * exceptions because wp_mail can throw on malformed inputs and we
     * don't want a notification failure to bubble up into checkout.
     */
    private static function send(string $to, string $subject, string $body): bool
    {
        try {
            return (bool) wp_mail(
                $to,
                $subject,
                $body,
                [
                    self::FROM_HEADER,
                    'Content-Type: text/plain; charset=UTF-8',
                ]
            );
        } catch (\Throwable $e) {
            error_log(sprintf(
                '[MailNotifications] wp_mail threw for %s: %s',
                $to,
                $e->getMessage()
            ));
            return false;
        }
    }
}
