<?php
/**
 * Server-side rendering for the Hero block.
 *
 * This file is referenced in block.json in the 'render' key.
 *
 * @param array $attributes Block attributes.
 * @param string $content The block content (serialized HTML of inner blocks).
 * @param WP_Block $block The block instance.
 * @return string HTML markup for the hero block.
 */

// --- IDE Hints (for static analysis only) ---
// These @var tags tell PHPStorm (and other tools) that these variables
// exist in this file's scope and what their types are, even though
// they are not defined using the '=' operator within this file.
/** @var array $attributes */
/** @var string $content */ // This $content contains the rendered InnerBlocks HTML
/** @var WP_Block $block */


$title = $attributes['title'] ?? '';
$subtitle = $attributes['subtitle'] ?? '';
$svg_asset = $attributes['svgAsset'] ?? '';

// get_block_wrapper_attributes automatically includes alignment and InnerBlocks classes
$wrapper_attributes = get_block_wrapper_attributes();
// Manually add the 'hero' class to the wrapper attributes.
// get_block_wrapper_attributes() returns a string like 'class="wp-block-vincentragosta-hero alignfull"'
// We find the class attribute and insert our custom class.
$wrapper_attributes = str_replace(
    'class="',
    'class="hero ', // Add the 'hero' class here
    $wrapper_attributes
);
//ob_start(); // Start output buffering
?>
<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
    <div class="hero__content">
        <?php if (!empty($title)) : ?>
            <h1 class="hero__title"><?php echo wp_kses_post($title); ?></h1>
        <?php endif; ?>

        <?php if (!empty($subtitle)) : ?>
            <p class="hero__subtitle"><?php echo wp_kses_post($subtitle); ?></p>
        <?php endif; ?>

        <?php
        // RENDER INNER BLOCKS (THE BUTTONS)
        // The $content parameter already contains the rendered markup of all inner blocks.
        // Use this variable to output the buttons HTML.
        if (!empty($content)) :
            // Wrap inner blocks in the existing .hero-block__links div for layout
            echo '<div class="hero__links">';
            echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- $content is rendered block markup generated by WP core
            echo '</div>';
        endif;
        ?>
    </div>
    <div class="hero__svg">
        <?php if (!empty($svg_asset)): ?>
            <?= get_theme_svg($svg_asset); ?>
        <?php endif; ?>
    </div>
</div>