/**
 * Livestream Flow Reference — auto-synced to #livestream-flow on startup.
 *
 * Each entry is an embed posted in order. On startup, the bot compares
 * existing embeds to this content and updates any that have changed.
 */

const messages = [
    // Message 1: Before Going Live
    {
        title: '📋 Stream Night Flow',
        description: [
            '**Before Going Live**',
            '```',
            'Queue is already open (opened by previous !offline)',
            'Pre-orders are coming in automatically via Stripe webhook',
            '!queue                                → Check what\'s queued up tonight',
            '```',
            '',
            '**Pre-Stream Hype** (stream day, before going live)',
            '```',
            '!hype Product 1, Product 2            → Looks up products in Stripe',
            '                                         Shows preview with prices (detects sales)',
            '                                         Confirm with ✅ → posts to #announcements',
            '                                         Each product gets a Buy Now button',
            '```',
            '',
            '**Going Live**',
            '```',
            '!live                                 → Master switch ON',
            '                                         • Posts pre-order summary (queue stays OPEN)',
            '                                         • Starts livestream session (shipping-free mode)',
            '                                         • Posts going-live in #announcements with shop link',
            '```',
        ].join('\n'),
        color: 0x2ecc71,
    },

    // Message 2: During Stream
    {
        title: '🔴 During Stream',
        description: [
            '```',
            'Work through the queue on stream      → Open each buyer\'s packs on camera',
            'Viewers buy from shop link (?live=1)  → No shipping charged (collected after stream)',
            '',
            'CARD SALES:',
            '!sell @buyer "Card Name" 25.00        → Reserve for a viewer (15-min expiry)',
            '!list "Card Name" 25.00               → List for open purchase',
            '!pull "Pull Box" 3.00                 → Open pull box (unlimited buyers)',
            '!pull close                           → Close pull box, show revenue',
            '',
            'COUPON / FLASH DEAL:',
            '!coupon STREAM10                      → Activate promo code (shows field on checkout)',
            '!coupon off                           → Deactivate when deal window ends',
            '',
            'PACK BATTLE:',
            '!battle start Product Name 12         → Start battle',
            '!battle close                         → Close entries, show roster',
            '  → Open ALL packs on stream, check tcgrepublic.com',
            '!battle winner @user                  → Declare winner, assign Aha role',
            '',
            'ACTIVITY BREAK:',
            '!duckrace                             → Show duck race roster',
            '  → Run race at online-stopwatch.com/duck-race',
            '!duckrace winner @user                → Declare winner, assign Aha role',
            '',
            'GIVEAWAY (if active):',
            '!giveaway close                       → Close entries (if not auto-closed)',
            '!giveaway draw duckrace               → Load entries as duck race roster',
            '!giveaway draw                        → Or pick random winner directly',
            '',
            'AD-HOC:',
            '!shipping @user 10.00 [reason]        → Send a shipping checkout link',
            '!waive @user                          → Waive shipping (pre-waive or refund)',
            '!refund @user [amount] [reason]       → Refund most recent purchase',
            '!sold <message_id>                    → Mark a card listing as sold',
            '```',
            '',
            '**After 4 Hours**',
            '```',
            'Bot DMs you a reminder if !offline hasn\'t been run (just a nudge)',
            '```',
        ].join('\n'),
        color: 0x2ecc71,
    },

    // Message 3: End of Stream
    {
        title: '📴 End of Stream',
        description: [
            '```',
            '!offline                              → Master switch OFF',
            '                                         • Ends livestream session',
            '                                         • Disables shipping-free mode',
            '                                         • Closes queue, archives to #card-night-queue',
            '                                         • Splits buyers: domestic/international/covered',
            '                                         • DMs $10 to domestic, $25 to international',
            '                                         • Skips buyers already covered this week/month',
            '                                         • Opens next pre-order queue',
            '                                         • Posts stream-ended in #announcements',
            '                                         • Posts stream recap to #analytics',
            '```',
            '',
            '**Note:** Discord purchases (button checkouts) handle shipping proactively — those buyers won\'t appear in !offline. Only WordPress `?live=1` buyers need shipping here.',
        ].join('\n'),
        color: 0x2ecc71,
    },

    // Message 4: Card Night Structure
    {
        title: '🃏 Card Night Structure',
        description: [
            'Three streams per card night. All vibes-based — no hard clock.',
            '',
            '**Stream 1: Card Night (Pokemon + Anime)**',
            'Simulcast: Twitch + YouTube (OBS) and TikTok + Instagram (iPad)',
            '```',
            'Open           → Welcome, tonight\'s lineup, show products, hype chat',
            'Pokemon        → Pack openings, product showcase, pack battles',
            'Activity break → Duck race, wheel spin, giveaway draw, pack battle finals',
            'Anime          → Weiss Schwarz, anime product showcase, pack battles',
            'Activity break → Second duck race or flash deal announcement',
            'Wind down      → Recap best pulls, thank buyers, shout out Discord',
            'Close          → "Switching to After Dark on Twitch + IG"',
            '```',
            '',
            '**Stream 2: After Dark** (Twitch + Instagram only)',
            'End YouTube and TikTok simulcast first. Enable Twitch mature tag.',
            'Same format — mature product (Goddess Story, mature playmats). Pack battles, duck races, same revenue activities.',
            '',
            '> "Thanks for watching on YouTube and TikTok — switching to Twitch and Instagram only for After Dark. 18+ from here."',
            '',
            '**Stream 3: Gaming**',
            'Simulcast: Twitch + YouTube (OBS) and TikTok (iPad). No fixed structure. Vibes.',
            '```',
            'Dailies        → HSR + ZZZ (~30 min) — low-key warmup',
            'Main game      → Fortnite squads, Minecraft, or Marvel Rivals',
            '                  Go as long as it feels right',
            '```',
        ].join('\n'),
        color: 0x2ecc71,
    },

    // Message 5: Shipping Reference & Quick Links
    {
        title: '📦 Shipping Reference',
        description: [
            '**Domestic (US): $10/week  •  International (CA+): $25/month**',
            '```',
            'Normal shop (domestic)         →  $10 at checkout',
            'Normal shop (international)    →  $25 at checkout (country toggle)',
            'Livestream (?live=1)           →  Free → DM after !offline',
            'Discord buttons (!list/!hype)  →  Bot checks → $10/$25 or skip',
            'Pack battle buy-in             →  Bot checks → $10/$25 or skip',
            'Ad-hoc (!shipping @user amt)   →  Any amount, DM with checkout link',
            '```',
            '',
            '*One payment covers all purchases for the period. Already paid = skipped.*',
            '',
            '**Quick Links**',
            '```',
            'Duck race timer   → online-stopwatch.com/duck-race',
            'Card values       → tcgrepublic.com',
            'Shop              → vincentragosta.io/shop',
            'Pricing formula   → cost × 1.45, round up',
            '```',
        ].join('\n'),
        color: 0x2ecc71,
    },

    // Message 6: Revenue Notes
    {
        title: '💰 Revenue Notes',
        description: [
            '```',
            'Pack battle math:',
            '  12 entries × full retail = 12 packs sold, winner gets all cards',
            '  The entertainment IS the value-add — no discounts',
            '',
            'Duck race cost:',
            '  1 free pack per race × 2 races per stream = ~$8-10/night',
            '  This is customer acquisition cost — worth it',
            '',
            'Activity breaks between segments:',
            '  1. Reward buyers publicly (encourages more purchases)',
            '  2. Create clip-worthy moments for TikTok/YouTube',
            '  3. Give you breathing room between selling segments',
            '',
            '?live=1 security:',
            '  Server-side WordPress transient — !live sets it, !offline clears it',
            '  Manually adding ?live=1 when not live does nothing',
            '  Auto-expires after 12 hours as safety net',
            '```',
        ].join('\n'),
        color: 0x2ecc71,
    },
];

export default messages;
