export const backgroundColorFixture: string[] = [
  "bgPrimary",
  "bgPrimaryDark",
  "bgPrimaryLight",
  "bgSecondary",
  "bgSecondaryDark",
  "bgSecondaryLight",
  "bgTertiary",
  "bgTertiaryDark",
  "bgTertiaryLight",
  "bgGrayDark",
  "bgGray",
  "bgGrayLight",
  "bgOffWhite",
  "bgWhite",
  "bgBlack",
];
